-- Dati di esempio — plausibili ma da confermare col cliente prima della
-- pubblicazione reale (vedi README del design). Le date sono relative a
-- "now()" così restano sempre "prossime uscite" ogni volta che il seed
-- viene eseguito.

insert into escursioni (
  titolo, descrizione, descrizione_breve, richiede_codice_fiscale, zona,
  punto_di_ritrovo, dislivello, lunghezza_percorso, durata, difficolta,
  data_ora, prezzo, posti_totali, embed_mappa, stato, foto
) values
(
  'Anello del Monte Cavallo',
  'Un anello panoramico che sale dal piazzale di Piancavallo fino alla cresta del Monte Cavallo, con vista sulla pianura friulana e, nelle giornate limpide, fino al mare. Percorso impegnativo ma alla portata di chi ha un minimo di allenamento: saliamo con calma, ci fermiamo spesso a guardare, e torniamo per un sentiero diverso da quello dell''andata.',
  'Cresta panoramica su Piancavallo, vista mare nelle giornate limpide.',
  false,
  'Piancavallo',
  'Piazzale Genziana, Piancavallo (PN) — parcheggio principale',
  '900 m D+',
  '11 km',
  '6 ore',
  'Difficile',
  now() + interval '9 days' + time '08:30',
  35.00,
  12,
  '<iframe src="https://www.komoot.com/it-it/smoothie/123456" width="100%" height="360" frameborder="0"></iframe>',
  'pubblicata',
  null
),
(
  'I mulini di Polcenigo e la Santissima',
  'Passeggiata tranquilla tra le risorgive del Gorgazzo e i mulini storici di Polcenigo, fino alla sorgente della Santissima. Percorso quasi pianeggiante, adatto alle famiglie con bambini che camminano da soli (il tratto finale non è adatto ai passeggini). Tante soste per raccontare la storia dei mulini e osservare la fauna del torrente.',
  'Passeggiata alle sorgenti, adatta alle famiglie.',
  false,
  'Polcenigo',
  'Parcheggio di Piazza Plebiscito, Polcenigo (PN)',
  '220 m D+',
  '6 km',
  '3 ore',
  'Facile',
  now() + interval '16 days' + time '09:30',
  20.00,
  20,
  null,
  'pubblicata',
  null
),
(
  'Diga del Vajont: la memoria e il bosco',
  'Camminiamo lungo la diga del Vajont e sopra Erto e Casso, tra i boschi che negli ultimi sessant''anni hanno ripreso il versante. Un percorso di media difficoltà che è anche un momento di memoria: raccontiamo cosa è successo nel 1963 e come il territorio convive oggi con quella storia.',
  null,
  false,
  'Erto e Casso',
  'Belvedere della Diga del Vajont, Erto e Casso (PN)',
  '400 m D+',
  '9 km',
  '4 ore',
  'Medio',
  now() + interval '30 days' + time '09:00',
  25.00,
  15,
  '<iframe src="https://mapy.cz/s/embed/123abc" width="100%" height="360" frameborder="0"></iframe>',
  'pubblicata',
  null
),
(
  'Val Colvera: il sentiero dei mulattieri',
  'Un cammino storico lungo l''antica via dei mulattieri che collegava la Val Colvera alla Val Tramontina, tra boschi di faggio e piccoli borghi quasi abbandonati. Difficoltà media, fondo per lo più naturale.',
  null,
  false,
  'Val Colvera',
  'Chiesa di Frisanco (PN)',
  '550 m D+',
  '10 km',
  '5 ore',
  'Medio',
  now() + interval '23 days' + time '08:00',
  25.00,
  14,
  null,
  'pubblicata',
  null
),
(
  'Alba sulle Dolomiti Friulane',
  'Uscita speciale all''alba: partenza al buio con le frontali, salita fino a un belvedere panoramico per vedere il sole sorgere sulle Dolomiti Friulane, colazione condivisa in vetta e rientro in mattinata. Gruppo ristretto per godersi il silenzio.',
  'Uscita all''alba con colazione in vetta, gruppo ristretto.',
  false,
  'Dolomiti Friulane',
  'Da definire in base al meteo — comunicato ai partecipanti il giorno prima',
  '600 m D+',
  '8 km',
  '4 ore',
  'Medio',
  now() + interval '37 days' + time '05:00',
  30.00,
  8,
  null,
  'pubblicata',
  null
),
(
  'Malghe della Val Tramontina',
  'Anello tra le malghe ancora attive della Val Tramontina, con possibilità di assaggiare i formaggi di malga a fine escursione (facoltativo, a carico dei partecipanti). Percorso facile su sterrato e sentiero.',
  null,
  false,
  'Val Tramontina',
  'Parcheggio del Lago di Redona (PN)',
  '300 m D+',
  '7 km',
  '3 ore e mezza',
  'Facile',
  now() + interval '44 days' + time '09:00',
  20.00,
  18,
  null,
  'pubblicata',
  null
),
(
  'Forra del Cellina',
  'Cammino sospeso sulla forra del torrente Cellina, tra passerelle e tratti scavati nella roccia. Panorami spettacolari, ma alcuni tratti esposti richiedono passo sicuro: non adatta a chi soffre di vertigini.',
  null,
  false,
  'Barcis',
  'Diga di Barcis (PN)',
  '250 m D+',
  '5 km',
  '3 ore',
  'Medio',
  now() + interval '51 days' + time '09:00',
  22.00,
  16,
  null,
  'pubblicata',
  null
),
(
  'Uscita scuole — sentiero natura (bozza)',
  'Mezza giornata di educazione ambientale per una classe di scuola primaria: bozza in preparazione, dettagli e data da confermare con l''istituto.',
  null,
  false,
  'Budoia',
  'Da confermare',
  '100 m D+',
  '3 km',
  '2 ore',
  'Facile',
  now() + interval '60 days' + time '09:00',
  0,
  25,
  null,
  'bozza',
  null
),
(
  'Uscita di prova conclusa',
  'Escursione di collaudo del sito, già svolta: serve solo a verificare che le uscite passate non compaiano nell''elenco pubblico.',
  null,
  false,
  'Piancavallo',
  'Piazzale Genziana, Piancavallo (PN)',
  '400 m D+',
  '6 km',
  '3 ore',
  'Facile',
  now() - interval '10 days',
  20.00,
  10,
  null,
  'conclusa',
  null
);
